export const GAME_CHANGED = "gameChanged";

export const GET_TEAMS = "getTeams";

export const GET_ONGOING_MATCHES = "GET_ONGOING_MATCHES"
export const GET_ONGOING_MATCHES_SUCCESS = "GET_ONGOING_MATCHES_SUCCESS"
export const GET_ONGOING_MATCHES_FAIL = "GET_ONGOING_MATCHES_FAIL"

export const GET_UPCOMING_MATCHES = "getUpcomingMatches"
export const GET_UPCOMING_MATCHES_SUCCESS = "GET_UPCOMING_MATCHES_SUCCESS"
export const GET_UPCOMING_MATCHES_FAIL = "GET_UPCOMING_MATCHES_FAIL"

export const GET_PAST_MATCHES = "getPastMatches"
export const GET_PAST_MATCHES_SUCCESS = "GET_PAST_MATCHES_SUCCESS"
export const GET_PAST_MATCHES_FAIL = "GET_PAST_MATCHES_FAIL"