export const GET_USERS = "GET_USERS";
export const GET_USER_DETAILS = "GET_USER_DETAILS"
export const GET_PRODUCTS = "GET_PRODUCTS"
export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS"
export const SAVE_ADMIN = "SAVE_ADMIN"